# Utilise l'image Node.js comme base
FROM node:14

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Installer Vue CLI globalement
RUN npm install -g @vue/cli

# Copier le package.json et le package-lock.json dans le conteneur
COPY package* ./

# Installer les dépendances du projet
RUN npm install

# Copier le reste des fichiers de l'application
COPY . .

# Exposer le port
EXPOSE 8080

# Commande pour lancer l'application
CMD ["npm", "run", "serve"]
