version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - ALLOWED_HOSTS=localhost,0.0.0.0,127.0.0.1
      - REDIS_URL=redis://redis:6379/0  # Ajout de REDIS_URL
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ma_cantine
      POSTGRES_USER: ma_cantine_user
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6  # Ajout du service Redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
